# Generated by Django 5.1.2 on 2024-11-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0003_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(default="2024-11-01 13:45:24"),
        ),
    ]
