# Generated by Django 5.1.2 on 2024-11-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0004_review_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="razorpay_payment_signature",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(default="2024-11-03 18:05:07"),
        ),
    ]
