# Generated by Django 5.1.2 on 2024-11-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0006_profile_subscription_alter_review_created_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
        migrations.AddField(
            model_name="profile",
            name="image_left",
            field=models.IntegerField(default=5, max_length=100),
        ),
    ]
