# Generated by Django 5.1.2 on 2024-11-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0007_delete_review_profile_image_left"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image_left",
            field=models.IntegerField(default=5),
        ),
    ]
