# Generated by Django 5.1.2 on 2024-11-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0008_alter_profile_image_left"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="subscription",
            field=models.CharField(default="free", max_length=10),
        ),
    ]
