# Generated by Django 5.1.3 on 2024-11-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0009_alter_profile_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="images_generated",
            field=models.ManyToManyField(related_name="profiles", to="App.image"),
        ),
    ]
