# Generated by Django 5.1.3 on 2024-11-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0010_image_profile_images_generated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="images_generated",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="App.image"
            ),
        ),
    ]
