# Generated by Django 5.1.3 on 2024-11-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0011_alter_profile_images_generated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="images_generated",
        ),
        migrations.AddField(
            model_name="profile",
            name="images_generated",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
