# Generated by Django 5.1.3 on 2024-11-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0012_remove_profile_images_generated_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="subscription",
        ),
        migrations.AddField(
            model_name="profile",
            name="subscription_plan",
            field=models.CharField(default="Free", max_length=50),
        ),
    ]
