# Generated by Django 5.1.3 on 2024-11-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0013_remove_profile_subscription_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="razorpay_order_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="razorpay_payment_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="razorpay_payment_signature",
        ),
        migrations.AddField(
            model_name="profile",
            name="subscription_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
